import Head from "next/head";
import {
  Container,
  Main,
  Title,
  Description,
  CtaRow,
} from "../components/sharedstyles";
import Cards from "../components/cards";
import LogoComponent from "../components/logoComponent";
import ImageComponent from "../components/imageComponent";
import sLogo from "../public/gucci-bag.jpeg";

import LinkOrButton from "../components/LinkOrButton";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>NFMINTEA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <LogoComponent />
        <Title>ReSelfridges NFT</Title>
        <ImageComponent img={sLogo} badge />

        <Description>
          <h2 style={{ margin: 0 }}>Gucci Bag</h2>
        </Description>
        <Description>Vintage 2021</Description>
        <Description>Pre-owned / Pre-loved</Description>

        <CtaRow>
          <LinkOrButton href="/buy">BUY</LinkOrButton>
          <LinkOrButton href="/info">NFT INFO</LinkOrButton>
        </CtaRow>
      </Main>
    </Container>
  );
}
