import Head from "next/head";
import {
  Container,
  Main,
  Title,
  Description,
  CtaRow,
} from "../components/sharedstyles";
import Cards from "../components/cards";
import LogoComponent from "../components/logoComponent";
import ImageComponent from "../components/imageComponent";
import qR from "../public/qr.png";

import LinkOrButton from "../components/LinkOrButton";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>NFMINTEA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <LogoComponent />
        <Title>NFT DATA</Title>
        <ImageComponent img={qR} small />

        <Description>
          <h2 style={{ margin: 0 }}>Gucci Bag</h2>
        </Description>
        <Description>
          Transaction ID - <em>xxx-xxx-xxx</em>
        </Description>
        <Description>
          Condition - <em>5</em>
        </Description>
        <Description>
          <h3 style={{ margin: 0 }}>£999.99</h3>
        </Description>
        <CtaRow center>
          <LinkOrButton href="/buy">ADD TO CART</LinkOrButton>
        </CtaRow>
      </Main>
    </Container>
  );
}
